services:

  #
  # MDA 0.9.2 _without_ external Xalan processor
  #
  v09:
    image: ukf/testbed:0.9
    hostname: v09

  #
  # MDA 0.9.2 _with_ external Xalan processor
  #
  # This corresponds to the current production
  # environment, so we expose it on localhost:8080
  # as well as on the private network.
  #
  v09x:
    image: ukf/testbed:0.9-xalan
    hostname: v09x
    ports:
    - target: 8080
      published: 8080
      mode: host

  #
  # MDA 0.10.0 _without_ external Xalan processor
  #
  v010:
    image: ukf/testbed:0.10
    hostname: v010

  #
  # MDA 0.10.0 _with_ external Xalan processor
  #
  v010x:
    image: ukf/testbed:0.10-xalan
    hostname: v010x

  #
  # Test driver.
  #
  driver:
    image: ukf/testbed-driver:latest
    hostname: driver
    environment:
      RAILS_ENV: production
    volumes:
    - type: bind
      source: ./tests
      target: /application/tests
