services:

  #
  # MDA 0.10.0 _without_ external Xalan processor
  #
  # This corresponds to the current production
  # environment, so we expose it on localhost:8080
  # as well as on the private network.
  #
  prod:
    image: ukf/testbed:prod
    hostname: prod
    ports:
    - target: 8080
      published: 8080
      mode: host

  #
  # "next" is currently by default the same as "prod"
  #
  next:
    image: ukf/testbed:next
    hostname: next

  #
  # Test driver.
  #
  driver:
    image: ukf/testbed-driver:latest
    hostname: driver
    environment:
      RAILS_ENV: production
    volumes:
    - type: bind
      source: ./tests
      target: /application/tests
