#!/bin/bash

docker buildx build \
    --file Dockerfile.prod \
    --tag ukf/testbed:prod \
    --output type=docker \
    $@ \
    .

docker buildx build \
    --file Dockerfile.next \
    --tag ukf/testbed:next \
    --output type=docker \
    $@ \
    .
