#!/bin/bash

docker buildx build \
    --file Dockerfile.09 \
    --tag ukf/testbed:0.9 \
    --output type=docker \
    $@ \
    .

docker buildx build \
    --file Dockerfile.010 \
    --tag ukf/testbed:0.10 \
    --output type=docker \
    $@ \
    .

docker buildx build \
    --file Dockerfile.09x \
    --tag ukf/testbed:0.9-xalan \
    --output type=docker \
    $@ \
    .

docker buildx build \
    --file Dockerfile.010x \
    --tag ukf/testbed:0.10-xalan \
    --output type=docker \
    $@ \
    .
