FROM ianayoung/md-validator:0.10 AS build

WORKDIR /application

#
# Customise by modifying /application/BOOT-INF/...
#
ADD overlays/all   BOOT-INF/
ADD overlays/xalan BOOT-INF/
ADD overlays/010x  BOOT-INF/
