# frozen_string_literal: true

task :cop do
  system 'bundle exec rubocop'
end

def run_test(test_name)
  puts "Running test #{test_name}."
  system "bundle exec ruby -I lib tests/test_#{test_name}.rb"
  puts "Done #{test_name}.\n"
end

task :poke do
  system 'bundle exec ruby -I lib bin/poke_hosts.rb'
end

task :validate_all do
  system 'bundle exec ruby -I lib bin/validate_all.rb'
end

task default: %i[poke validate_all] do
  puts 'All tests done.'
end
