name: Docker Image CI For All Validators And Driver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_docker_images:
    name: Build driver and validator fleet images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the "prod" Docker image
      run: docker buildx build validators --file validators/Dockerfile.prod --tag ukf/testbed:prod --output type=docker
    - name: Build the "next" Docker image
      run: docker buildx build validators --file validators/Dockerfile.next --tag ukf/testbed:next --output type=docker
    - name: Build the driver Docker image
      run: docker buildx build driver --tag ukf/testbed-driver:latest --output type=docker
